import jsPDF from "jspdf";

// Plain JavaScript version – no TypeScript
export function generateInvoicePDF(data) {
  const { billItems, totalAmount, customerPhone } = data;
  
  if (!billItems || billItems.length === 0) {
    throw new Error("No items to generate invoice");
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 20, 30);
  
  // Invoice details
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 45);
  doc.text(`Invoice #: INV-${Date.now()}`, 20, 55);
  
  if (customerPhone) {
    doc.text(`Customer Phone: ${customerPhone}`, 20, 65);
  }
  
  // Company info (placeholder)
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("VoiceBill Pro", pageWidth - 60, 30);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Voice-Driven Billing Assistant", pageWidth - 60, 40);
  
  // Table header
  let yPosition = 85;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  
  doc.text("Item", 20, yPosition);
  doc.text("Quantity", 80, yPosition);
  doc.text("Rate", 120, yPosition);
  doc.text("Amount", 160, yPosition);
  
  // Header line
  yPosition += 5;
  doc.line(20, yPosition, pageWidth - 20, yPosition);
  
  // Table content
  doc.setFont("helvetica", "normal");
  billItems.forEach((item) => {
    yPosition += 12;
    
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.text(item.name, 20, yPosition);
    doc.text(String(item.quantity), 80, yPosition); // ✅ force string
    doc.text(`₹${Number(item.rate).toFixed(2)}`, 120, yPosition);
    doc.text(`₹${Number(item.amount).toFixed(2)}`, 160, yPosition);
  });
  
  // Total line
  yPosition += 10;
  doc.line(20, yPosition, pageWidth - 20, yPosition);
  
  // Total amount
  yPosition += 15;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Total: ₹${Number(totalAmount).toFixed(2)}`, 160, yPosition);
  
  // Footer
  yPosition += 30;
  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  doc.text("Thank you for your business!", 20, yPosition);
  doc.text("Generated by VoiceBill Pro", 20, yPosition + 10);
  
  // Save the PDF
  const fileName = `invoice-${Date.now()}.pdf`;
  doc.save(fileName);
}

// Helper: check if jsPDF works in the browser
export function isJsPDFSupported() {
  return typeof jsPDF !== "undefined";
}
